cadastros = [
    {'nome': 'Carlos Eduardo de Souza Sales',
     'CPF': '03973457123',
     'email': 'cadubss2@gmail.com',
     'raca': 'branca',
     'etnia': 'brasileiro',
     'escolaridade': 'ES',
     'nascimento': '06-11-2006',
     'genero': 'masc',
     'codigo': '27341'},
     
     {'nome': 'Carlos Eduardo de Souza Sales',
     'CPF': '03973457123',
     'email': 'cadubss2@gmail.com',
     'raca': 'branca',
     'etnia': 'brasileiro',
     'escolaridade': 'ES',
     'nascimento': '06-11-2006',
     'genero': 'masc',
     'codigo': '27341'},
     
     {'nome': 'Carlos Eduardo de Souza Sales',
     'CPF': '03973457123',
     'email': 'cadubss2@gmail.com',
     'raca': 'branca',
     'etnia': 'brasileiro',
     'escolaridade': 'ES',
     'nascimento': '06-11-2006',
     'genero': 'masc',
     'codigo': '27341'},
     
     {'nome': 'Carlos Eduardo de Souza Sales',
     'CPF': '03973457123',
     'email': 'cadubss2@gmail.com',
     'raca': 'branca',
     'etnia': 'brasileiro',
     'escolaridade': 'ES',
     'nascimento': '06-11-2006',
     'genero': 'masc',
     'codigo': '27341'},

     {'nome': 'Carlos Eduardo de Souza Sales',
     'CPF': '03973457123',
     'email': 'cadubss2@gmail.com',
     'raca': 'branca',
     'etnia': 'brasileiro',
     'escolaridade': 'ES',
     'nascimento': '06-11-2006',
     'genero': 'masc',
     'codigo': '27341'}
]